version: '3.7'
services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - TZ=America/Sao_Paulo
    ports:
      - "5432"

  web:
    build: .
    command: zsh -c "bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    platform: linux/x86_64
    stdin_open: true
    tty: true
    volumes:
      - bundle_cache:/bundle
      - .:/app
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  bundle_cache: